import type { SolverSettings } from "../types/settings";

export const DEFAULT_RATING_RANGE: [number, number] = [65, 93];
export const DEFAULT_SPECIAL_FUEL_RATING_RANGE: [number, number] = [0, 99];

export const defaultSolverSettings: SolverSettings = {
  apiUrl: "http://127.0.0.1:8000",
  backendPort: 8000,
  eaRequestMaxAttempts: 3,
  eaRequestRetryDelaySeconds: 3,
  eaSbcRequestIntervalMs: 900,
  excludeTeams: [],
  excludeRarity: [],
  excludeNations: [],
  excludeLeagues: [],
  excludeSbc: false,
  excludeTradable: false,
  excludeObjective: false,
  excludeExtinct: false,
  excludeSbcSquads: false,
  onlyStorage: false,
  useConcepts: false,
  collectConcepts: false,
  animateWalkouts: 98,
  autoSubmit: 1,
  maxSolveTime: 10,
  squadRatingOvershoot: 1.8,
  priceCacheMinutes: 1440,
  ratingRange: [...DEFAULT_RATING_RANGE],
  priceRange: [null, null],
  commonOnly: false,
  allowExtraRequiredRarityGroupPlayers: false,
  specialFuelRulesEnabled: false,
  specialFuelRatingRange: [...DEFAULT_SPECIAL_FUEL_RATING_RANGE],
  specialFuelPriceRange: [null, null],
  specialFuelOnlyStorage: false,
  specialFuelStorageRulesEnabled: false,
  specialFuelStorageRatingRange: [...DEFAULT_SPECIAL_FUEL_RATING_RANGE],
  showPrices: true,
  showSbcTab: true,
  useDupes: true,
  sbcAllGroup: true,
  autoOpenPacks: false,
  packAutoPick: true,
  packPickStrategy: "ovr",
  packQuickSellDuplicates: true,
  packQuickSellUnder: 80,
  packSkipAnimation: true,
  sbcType: "Favourites",
  duplicateDiscount: 50,
  untradeableDiscount: 80,
  conceptPremium: 10,
  evoPremium: 2,
  ratingUI: false,
  submitHourLimit: 90,
  submitDayLimit: 300,
};
